"""initial GeoNex schema

Revision ID: 4fe6838daedc
Revises: 
Create Date: 2026-09-22 17:39:17.344890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '4fe6838daedc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earthquake_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('depth_km', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('epicenter', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_earthquake_epicenter', 'earthquake_events', ['epicenter'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_earthquake_events_occurred_at'), 'earthquake_events', ['occurred_at'], unique=False)
    op.create_table('infrastructure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('HOSPITAL', 'SCHOOL', 'BRIDGE', 'GOVERNMENT_BUILDING', 'POWER_STATION', 'COMMUNICATION_TOWER', 'HELIPAD', 'OTHER', name='infrastructure_category'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_category'), 'infrastructure', ['category'], unique=False)
    op.create_index(op.f('ix_infrastructure_name'), 'infrastructure', ['name'], unique=False)
    op.create_table('landslide_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('artifact_url', sa.String(length=512), nullable=True),
    sa.Column('features_list', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    op.create_table('rainfall_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.String(length=100), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rainfall_1h', sa.Float(), nullable=False),
    sa.Column('rainfall_24h', sa.Float(), nullable=False),
    sa.Column('rainfall_3d', sa.Float(), nullable=False),
    sa.Column('rainfall_7d', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rainfall_obs_location', 'rainfall_observations', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_rainfall_observations_observed_at'), 'rainfall_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_rainfall_observations_station_id'), 'rainfall_observations', ['station_id'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'WATCH', 'WARNING', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_created_at'), 'risk_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_predictions_risk_level'), 'risk_predictions', ['risk_level'], unique=False)
    op.create_table('roads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('road_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roads_name'), 'roads', ['name'], unique=False)
    op.create_table('sar_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite', sa.String(length=50), nullable=False),
    sa.Column('bounding_box', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('coherence_loss', sa.Float(), nullable=False),
    sa.Column('displacement_mm', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sar_obs_bbox', 'sar_observations', ['bounding_box'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sar_observations_acquired_at'), 'sar_observations', ['acquired_at'], unique=False)
    op.create_table('soil_moisture_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('volumetric_water_content', sa.Float(), nullable=False),
    sa.Column('soil_depth_cm', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_moisture_observations_observed_at'), 'soil_moisture_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_soil_moisture_observations_sensor_id'), 'soil_moisture_observations', ['sensor_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'FIELD_OFFICER', 'ADMIN', 'DISTRICT_ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_district'), 'villages', ['district'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_prediction_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'WATCH', 'WARNING', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'EXPIRED', name='alert_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('geographic_area', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_prediction_id'], ['risk_predictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_area', 'alerts', ['geographic_area'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('field_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_report_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('CRACK', 'ROCKFALL', 'LANDSLIDE', 'DEBRIS', 'ROAD_DAMAGE', 'WATER_SEEPAGE', 'OTHER', name='report_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_INFORMATION', name='report_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('capture_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_reports_client_report_id'), 'field_reports', ['client_report_id'], unique=True)
    op.create_index(op.f('ix_field_reports_status'), 'field_reports', ['status'], unique=False)
    op.create_index(op.f('ix_field_reports_user_id'), 'field_reports', ['user_id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'PUSH', 'APP', 'EMAIL', name='delivery_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='delivery_status'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    op.create_table('field_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('VERIFY', 'REJECT', 'NEEDS_INFORMATION', name='verification_decision'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['field_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='media_type'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['field_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_report_id'), 'media', ['report_id'], unique=False)
   # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_media_report_id'), table_name='media')
    op.drop_table('media')
    op.drop_table('field_verifications')
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_field_reports_user_id'), table_name='field_reports')
    op.drop_index(op.f('ix_field_reports_status'), table_name='field_reports')
    op.drop_index(op.f('ix_field_reports_client_report_id'), table_name='field_reports')
    op.drop_index('idx_field_reports_location', table_name='field_reports', postgresql_using='gist')
    op.drop_table('field_reports')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index('idx_alerts_area', table_name='alerts', postgresql_using='gist')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_district'), table_name='villages')
    op.drop_index('idx_villages_location', table_name='villages', postgresql_using='gist')
    op.drop_table('villages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_soil_moisture_observations_sensor_id'), table_name='soil_moisture_observations')
    op.drop_index(op.f('ix_soil_moisture_observations_observed_at'), table_name='soil_moisture_observations')
    op.drop_index('idx_soil_moisture_observations_location', table_name='soil_moisture_observations', postgresql_using='gist')
    op.drop_table('soil_moisture_observations')
    op.drop_index(op.f('ix_sar_observations_acquired_at'), table_name='sar_observations')
    op.drop_index('idx_sar_obs_bbox', table_name='sar_observations', postgresql_using='gist')
    op.drop_table('sar_observations')
    op.drop_index(op.f('ix_roads_name'), table_name='roads')
    op.drop_index('idx_roads_geometry', table_name='roads', postgresql_using='gist')
    op.drop_table('roads')
    op.drop_index(op.f('ix_risk_predictions_risk_level'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_created_at'), table_name='risk_predictions')
    op.drop_index('idx_risk_predictions_location', table_name='risk_predictions', postgresql_using='gist')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_rainfall_observations_station_id'), table_name='rainfall_observations')
    op.drop_index(op.f('ix_rainfall_observations_observed_at'), table_name='rainfall_observations')
    op.drop_index('idx_rainfall_obs_location', table_name='rainfall_observations', postgresql_using='gist')
    op.drop_table('rainfall_observations')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('idx_landslide_inventory_location', table_name='landslide_inventory', postgresql_using='gist')
    op.drop_table('landslide_inventory')
    op.drop_index(op.f('ix_infrastructure_name'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_category'), table_name='infrastructure')
    op.drop_index('idx_infrastructure_location', table_name='infrastructure', postgresql_using='gist')
    op.drop_table('infrastructure')
    op.drop_index(op.f('ix_earthquake_events_occurred_at'), table_name='earthquake_events')
    op.drop_index('idx_earthquake_epicenter', table_name='earthquake_events', postgresql_using='gist')
    op.drop_table('earthquake_events')
    # ### end Alembic commands ###
